/*
* This file is automatically generated by px_generate_mixers.py - do not edit.
*/

#ifndef _AVIATA_MIXER_MULTI_TABLES
#define _AVIATA_MIXER_MULTI_TABLES

#define AVIATA_NUM_DRONES 4
#define AVIATA_NUM_ROTORS 6
#define AVIATA_MAX_MISSING_DRONES 0

static constexpr float _config_aviata_drone_angle[] {
	 0.785398, // 45.0 degrees
	 2.356194, // 135.0 degrees
	-2.356194, // -135.0 degrees
	-0.785398, // -45.0 degrees
};

static constexpr float _config_aviata_drone_angle_cos[] {
	 0.707107,
	-0.707107,
	-0.707107,
	 0.707107,
};

static constexpr float _config_aviata_drone_angle_sin[] {
	 0.707107,
	 0.707107,
	-0.707107,
	-0.707107,
};

static constexpr float _config_aviata_relative_drone_angle[][4] {
	{  0.000000, -1.570796,  3.141593,  1.570796, },
	{  1.570796,  0.000000, -1.570796,  3.141593, },
	{ -3.141593,  1.570796,  0.000000, -1.570796, },
	{ -1.570796, -3.141593,  1.570796,  0.000000, },
};

static constexpr float _config_aviata_relative_drone_angle_cos[][4] {
	{  1.000000,  0.000000, -1.000000,  0.000000, },
	{  0.000000,  1.000000, -0.000000, -1.000000, },
	{ -1.000000, -0.000000,  1.000000,  0.000000, },
	{  0.000000, -1.000000,  0.000000,  1.000000, },
};

static constexpr float _config_aviata_relative_drone_angle_sin[][4] {
	{  0.000000, -1.000000,  0.000000,  1.000000, },
	{  1.000000,  0.000000, -1.000000,  0.000000, },
	{ -0.000000,  1.000000,  0.000000, -1.000000, },
	{ -1.000000, -0.000000,  1.000000,  0.000000, },
};

enum class AviataMultirotorGeometry : MultirotorGeometryUnderlyingType {
	AVIATA_MISSING_,               // AVIATA with these drones missing:  (text key aviata_missing_)

	MAX_GEOMETRY
}; // enum class AviataMultirotorGeometry

namespace {
static constexpr MultirotorMixer::Rotor _config_aviata_aviata_missing_[] {
	{ -0.030201,  0.030201, -0.032942,  0.774201 },
	{ -0.030201,  0.030201,  0.032942,  0.774201 },
	{ -0.030201,  0.030201, -0.413627,  0.774201 },
	{ -0.030201,  0.030201, -0.413627,  0.774201 },
	{ -0.030201,  0.030201,  0.413627,  0.774201 },
	{ -0.030201,  0.030201,  0.413627,  0.774201 },
	{ -0.030201, -0.030201, -0.032942,  0.774201 },
	{ -0.030201, -0.030201,  0.032942,  0.774201 },
	{ -0.030201, -0.030201, -0.413627,  0.774201 },
	{ -0.030201, -0.030201, -0.413627,  0.774201 },
	{ -0.030201, -0.030201,  0.413627,  0.774201 },
	{ -0.030201, -0.030201,  0.413627,  0.774201 },
	{  0.030201, -0.030201, -0.032942,  0.774201 },
	{  0.030201, -0.030201,  0.032942,  0.774201 },
	{  0.030201, -0.030201, -0.413627,  0.774201 },
	{  0.030201, -0.030201, -0.413627,  0.774201 },
	{  0.030201, -0.030201,  0.413627,  0.774201 },
	{  0.030201, -0.030201,  0.413627,  0.774201 },
	{  0.030201,  0.030201, -0.032942,  0.774201 },
	{  0.030201,  0.030201,  0.032942,  0.774201 },
	{  0.030201,  0.030201, -0.413627,  0.774201 },
	{  0.030201,  0.030201, -0.413627,  0.774201 },
	{  0.030201,  0.030201,  0.413627,  0.774201 },
	{  0.030201,  0.030201,  0.413627,  0.774201 },
};

static constexpr const MultirotorMixer::Rotor *_config_aviata_index[] {
	&_config_aviata_aviata_missing_[0],
};

static constexpr unsigned _config_aviata_rotor_count[] {
	24, /* aviata_missing_ */
};

__attribute__((unused)) // Not really unused, but fixes compilation error
const char* _config_aviata_key[] {
	"aviata_missing_",	/* aviata_missing_ */
};

} // anonymous namespace

#endif /* _AVIATA_MIXER_MULTI_TABLES */


