import constants_aviata as constants_selection
import generate_matrices_aviata as generate_matrices_selection
constants = constants_selection
generate_matrices = generate_matrices_selection
generate_matrices.configure_constants(constants)
