import numpy as np

# AVIATA CONSTANTS
Ct = 6.295 # Newtons of force generated by a single rotor at max power
Cm = Ct * 0.05 # Newton-meters of torque generated by a single rotor at max power
num_rotors = 6 # Number of rotors on a single drone
r = 0.550 / 2 # Distance of each rotor from the center the drone (meters)
R = 1.25 # Distance between the center of a drone and the center of the structure (meters)
num_drones = 8 # Maximum number of drones on the structure

# These are just approximates, and we make things simple by assuming these are constant regardless of the number of drones on the structure
# TODO Maybe it's not too much trouble to calculate these for different configurations of drones
M_drone = 1.769 # mass of a single drone in kg
M = (M_drone * num_drones) * 1.25 # mass of the structure + drones + payload in kg (currently estimated as 125% of total drone weight)

I_v = M_drone * R*R * num_drones * 1.25 # rough vertical moment of inertia estimate
I_h = I_v / 2 # rough horizontal moment of inertia estimate

I = np.array([[I_h, 0.0, 0.0],
              [0.0, I_h, 0.0],  # moment of inertia tensor of the structure + drones + payload in kg*m^2
              [0.0, 0.0, I_v]]) 
Iinv = np.linalg.inv(I)
