uint8 command  # message types defined in network.hpp
int8 param -1    # used for docking requests (default -1) or increment leader

# Unused:
# string drone_id 
# setpoint # expand to leader needs
---
uint8 ack       # acknowledgment
